- packages/cli/src/index.js
> fix(cli): executable portability issue

- packages/docs/src/docs/main/components/features.js
Thanks a lot for building this! It looks awesome.
I am going to share link to this project in http://t.me/opensource_findings
I hope this will help your project a bit 🙂
> fix(docs): makes dots consistent in features description

- packages/core/src/type-graph/type-graph.js
- packages/core/tests/type-assertion.test.js
Inspired by OCaml
What do you think about it? 
PS I would like to see more comments in the codebase, it would be very helpful for people with contribution
> fix(core): now you can call function as side effect only if it returns nothing

- packages/typings/standard/index.d.ts
> Fix Array.concat typings

- packages/core/src/type-graph/type-graph.js
- packages/docs/src/docs/try/components/hegel.js
> fix(Issue #143): record type alias position to show it on hover

- packages/core/.gitignore
- packages/core/src/inference/function-type.js
- packages/core/tests/type-graph.test.js
> fix "Rest arguments don't work with generics"

- packages/typings/standard/index.d.ts
I hope that I correctly understand the task (#154), if I done something wrong please let me know, and I will try to fix it.
It is a bit crazy to make commit for each line, but I want to provide reference where I take exceptions list. I think it would be better to squash it.
> Annotate exceptions in packages / standard / Structured data

- .github/workflows/deploy-docs.yml
> build(docs): add cache to CI build

- packages/language-server/server/hover/hover.js
- packages/language-server/server/server.js
- packages/language-server/server/utils/range.js
- packages/language-server/server/validation/code_validation.js
- packages/language-server/server/validation/typings.js
In last pull request hover does not work.  I fixed it.
> Fix hover feature

- packages/docs/src/docs/try/components/hegel.js
> process unexpected errors in try Hegel playground

- packages/docs/src/docs/docs/class-types.mdx
- packages/docs/src/docs/docs/function-types.mdx
- packages/docs/src/docs/docs/generic-types.mdx
- packages/docs/src/docs/docs/object-types.mdx
- packages/docs/src/docs/docs/primitive-types.mdx
- packages/docs/src/docs/docs/type-annotations.mdx
- packages/docs/src/docs/docs/union-types.mdx
- packages/docs/src/docs/docs/unknown-type.mdx
- packages/docs/src/docs/docs/what-and-why.mdx
this update examples following PR #117
> update examples to yield expected results

- packages/docs/src/docs/docs/installation.mdx
> fix(typo): wrong symbol fix

- packages/core/src/type-graph/type-graph.js
> fix(Issue #195): replace HegelError property 'path' by 'source'.

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
This copies over the README into the `build/` directory
so that it's included at publish time.
Whilst running the tests & developing in the repo I also
added
- `npm run build:watch` in the core directory as a utility for
local development.
- A couple of commits to update the `package-lock.json` as they
were out of date.
> Add README to build directory and npm package.

- packages/core/.babelrc
- packages/core/package.json
- packages/core/tests/preparation.js
- packages/core/tests/type-assertion.test.js
- packages/core/tests/type-definitions.test.js
- packages/core/tests/type-graph.test.js
- packages/core/tests/type-inference.test.js
- packages/core/tests/utility-types.test.js
- yarn.lock
> update @hegel/core tests

- README.md
this flag allow to not preprend each files with /*@flow*/
> add flow-remove-types option

- .github/workflows/ci.yml
Run tests on PRs and master commits in GitHub Actions CI for free
> Add unit tests to GitHub Actions CI

- .github/dependabot.yml
- .github/workflows/ci.yml
- packages/core/src/type-graph/call.js
- packages/docs/src/docs/docs/magic-types.mdx
Sorry I broke the tests with the Prettier changes
> Fix CI failures

- packages/cli/src/config.js
Just because it's nice to have :wink: Feel free to close this PR
> Ignore dotfiles/folders in project root by default

- packages/docs/src/docs/docs/what-and-why.mdx
Just thought it would be good to update the typescript version.
> New-typescript
